### ISSUE TITLE
Introscreen

### ISSUE THREAD

**Issue by maxpfe** [verdigado/gruene_app#321] opened 2024-11-04 15:15 UTC
After Splashscreen the user will see an introscreen with the following buttons: 'Jetzt einloggen' and 'App erkunden' -> App erkunden is no clickable in first release. Login leads to keycloak-login

**Comment by maxpfe** [comment] 2024-11-04 15:16
'unterstützen' button and 'login- für nichtmiglieder' not part of release 1

**Comment by JuliaFreitagBGSt** [comment] 2024-11-04 15:18
@leagerndt if new screenshots are necessary, pls provide and check user-flow

**Comment by steffenkleinle** [comment] 2024-11-08 09:14
Closing, duplicate of #209.

**Closed by steffenkleinle** 2024-11-08 09:14 UTC
Labels: Lead:verdigado, UX Design question, BTW: critical
